export const facilities = [
  {
    id: 'DCF-007-DUB', name: 'Dublin', region: 'EU', source: 'AUTO',
    submitted: true, timestamp: '2026-05-02 08:14', status: 'Submitted',
    pue: 1.28, energy: 58200, scope1: 12.4, scope2: 187.3, renewable: 78,
    confidence: 'Measured', water: 1820,
  },
  {
    id: 'DCF-002-FRA', name: 'Frankfurt', region: 'EU', source: 'AUTO',
    submitted: true, timestamp: '2026-05-03 11:42', status: 'Submitted',
    pue: 1.31, energy: 61400, scope1: 9.8, scope2: 198.2, renewable: 82,
    confidence: 'Measured', water: 1950,
  },
  {
    id: 'DCF-001-VA', name: 'N. Virginia', region: 'NA', source: 'AUTO',
    submitted: true, timestamp: '2026-05-01 09:00', status: 'Submitted',
    pue: 1.38, energy: 72100, scope1: 15.2, scope2: 231.4, renewable: 65,
    confidence: 'Measured', water: 2240,
  },
  {
    id: 'DCF-003-CHI', name: 'Chicago', region: 'NA', source: 'AUTO',
    submitted: true, timestamp: '2026-05-04 14:22', status: 'Submitted',
    pue: 1.35, energy: 68900, scope1: 11.8, scope2: 215.6, renewable: 71,
    confidence: 'Measured', water: 2100,
  },
  {
    id: 'DCF-004-SEA', name: 'Seattle', region: 'NA', source: 'MANUAL',
    submitted: true, timestamp: '2026-05-06 16:05', status: 'Submitted',
    pue: 1.41, energy: 54300, scope1: 8.4, scope2: 174.2, renewable: 88,
    confidence: 'Manual-Calculated', water: 1680,
  },
  {
    id: 'DCF-008-SIN', name: 'Singapore', region: 'APAC', source: 'MANUAL',
    submitted: false, timestamp: '—', status: 'Pending',
    pue: 1.67, energy: 47800, scope1: 18.6, scope2: 154.1, renewable: 41,
    confidence: 'Estimated', water: 1520,
  },
  {
    id: 'DCF-010-SAO', name: 'São Paulo', region: 'SA', source: 'MANUAL',
    submitted: false, timestamp: '—', status: 'Pending',
    pue: 1.58, energy: 39200, scope1: 14.2, scope2: 126.4, renewable: 35,
    confidence: 'Manual-Calculated', water: 1240,
  },
  {
    id: 'DCF-006-AMS', name: 'Amsterdam', region: 'EU', source: 'AUTO',
    submitted: true, timestamp: '2026-05-02 10:30', status: 'Submitted',
    pue: 1.30, energy: 55800, scope1: 7.6, scope2: 179.4, renewable: 91,
    confidence: 'Measured', water: 1740,
  },
  {
    id: 'DCF-005-PAR', name: 'Paris', region: 'EU', source: 'MANUAL',
    submitted: true, timestamp: '2026-05-07 13:15', status: 'Submitted',
    pue: 1.44, energy: 49600, scope1: 10.2, scope2: 159.7, renewable: 75,
    confidence: 'Manual-Calculated', water: 1580,
  },
  {
    id: 'DCF-009-SYD', name: 'Sydney', region: 'APAC', source: 'AUTO',
    submitted: true, timestamp: '2026-05-05 07:50', status: 'Submitted',
    pue: 1.36, energy: 43200, scope1: 9.1, scope2: 138.9, renewable: 62,
    confidence: 'Measured', water: 1360,
  },
  {
    id: 'DCF-011-TOR', name: 'Toronto', region: 'NA', source: 'AUTO',
    submitted: true, timestamp: '2026-05-03 08:00', status: 'Submitted',
    pue: 1.33, energy: 51700, scope1: 8.9, scope2: 165.3, renewable: 73,
    confidence: 'Measured', water: 1620,
  },
  {
    id: 'DCF-012-TOK', name: 'Tokyo', region: 'APAC', source: 'MANUAL',
    submitted: false, timestamp: '—', status: 'Pending',
    pue: 1.72, energy: 44100, scope1: 16.8, scope2: 141.6, renewable: 38,
    confidence: 'Estimated', water: 1410,
  },
];

export const kpiMetrics = [
  {
    key: 'pue',
    label: 'Average PUE',
    current: 1.42,
    target: 1.35,
    unit: '',
    targetLabel: '≤ 1.35',
    direction: 'lower',
    status: 'red',
    statusLabel: 'Off Track',
    sparkline: [
      { month: 'Dec', value: 1.49 },
      { month: 'Jan', value: 1.51 },
      { month: 'Feb', value: 1.48 },
      { month: 'Mar', value: 1.46 },
      { month: 'Apr', value: 1.44 },
      { month: 'May', value: 1.42 },
    ],
  },
  {
    key: 'carbon',
    label: 'Carbon Intensity',
    current: 187,
    target: 165,
    unit: 'kg CO₂/MWh',
    targetLabel: '≤ 165',
    direction: 'lower',
    status: 'amber',
    statusLabel: 'Watch',
    sparkline: [
      { month: 'Dec', value: 198 },
      { month: 'Jan', value: 195 },
      { month: 'Feb', value: 192 },
      { month: 'Mar', value: 190 },
      { month: 'Apr', value: 189 },
      { month: 'May', value: 187 },
    ],
  },
  {
    key: 'renewable',
    label: 'Renewable Energy',
    current: 61,
    target: 70,
    unit: '%',
    targetLabel: '≥ 70%',
    direction: 'higher',
    status: 'amber',
    statusLabel: 'Watch',
    sparkline: [
      { month: 'Dec', value: 56 },
      { month: 'Jan', value: 57 },
      { month: 'Feb', value: 58 },
      { month: 'Mar', value: 59 },
      { month: 'Apr', value: 60 },
      { month: 'May', value: 61 },
    ],
  },
  {
    key: 'water',
    label: 'Water Usage Index',
    current: 1.18,
    target: 1.10,
    unit: '',
    targetLabel: '≤ 1.10',
    direction: 'lower',
    status: 'red',
    statusLabel: 'Off Track',
    sparkline: [
      { month: 'Dec', value: 1.24 },
      { month: 'Jan', value: 1.23 },
      { month: 'Feb', value: 1.22 },
      { month: 'Mar', value: 1.21 },
      { month: 'Apr', value: 1.20 },
      { month: 'May', value: 1.18 },
    ],
  },
];

export const pueChartData = [
  { name: 'Dublin', pue: 1.28 },
  { name: 'Frankfurt', pue: 1.31 },
  { name: 'Amsterdam', pue: 1.30 },
  { name: 'Toronto', pue: 1.33 },
  { name: 'Chicago', pue: 1.35 },
  { name: 'Sydney', pue: 1.36 },
  { name: 'N. Virginia', pue: 1.38 },
  { name: 'Seattle', pue: 1.41 },
  { name: 'Paris', pue: 1.44 },
  { name: 'São Paulo', pue: 1.58 },
  { name: 'Singapore', pue: 1.67 },
  { name: 'Tokyo', pue: 1.72 },
];

export const portfolioTrendData = [
  { month: 'Jan', pue: 1.51 },
  { month: 'Feb', pue: 1.48 },
  { month: 'Mar', pue: 1.46 },
  { month: 'Apr', pue: 1.44 },
  { month: 'May', pue: 1.42 },
];
